package GamePlay0;
import java.awt.Color;
import javax.swing.colorchooser.ColorSelectionModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A.LoOotfy
 */
class Create_player 
{
    private Color color ;
    public Create_player(){
       
    }
    public Color getColor() {
        return color;
    }

    public void setColor(Color color) {
        this.color = color;
    }
}
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
     Create_player[] p ;
    public NewJFrame1() {
        initComponents();
       p = new Create_player[6];
       for (int i=0;i<6;i++){
           p[i] = new Create_player();
       }
       noOFplayer_pnl.setVisible(false);
       jColorChooser1.setVisible(false);
        player1_btn.setVisible(false);
        player2_btn.setVisible(false);
        player3_btn.setVisible(false);
        player4_btn.setVisible(false);
        player5_btn.setVisible(false);
        player6_btn.setVisible(false);
       pic1.setImage("src/monopoly.png", false);
       pic2.setImage("src/hat.png", false);
       pic3.setImage("src/hat.png", false);
       pic4.setImage("src/hat.png", false);
       pic5.setImage("src/hat.png", false);
       pic6.setImage("src/hat.png", false);
       pic7.setImage("src/hat.png", false);
       pic8.setImage("src/hat.png", false);
       pic9.setImage("src/hat.png", false);
       pic10.setImage("src/hat.png", false);
       pic11.setImage("src/hat.png", false);
       pic12.setImage("src/hat.png", false);
       pic13.setImage("src/hat.png", false);
       pic14.setImage("src/hat.png", false);
       pic15.setImage("src/hat.png", false);
       pic16.setImage("src/hat.png", false);
       pic17.setImage("src/hat.png", false);
       pic18.setImage("src/hat.png", false);
       pic19.setImage("src/hat.png", false);
       pic20.setImage("src/hat.png", false);
       pic21.setImage("src/hat.png", false);
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pic1 = new pic();
        start_btn = new javax.swing.JButton();
        NoOFplayer_btn = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        noOFplayer_pnl = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        pic2 = new pic();
        pic3 = new pic();
        player1_btn = new javax.swing.JButton();
        player2_btn = new javax.swing.JButton();
        player4_btn = new javax.swing.JButton();
        player3_btn = new javax.swing.JButton();
        player5_btn = new javax.swing.JButton();
        player6_btn = new javax.swing.JButton();
        jColorChooser1 = new javax.swing.JColorChooser();
        pic5 = new pic();
        pic4 = new pic();
        pic6 = new pic();
        pic7 = new pic();
        pic9 = new pic();
        pic8 = new pic();
        pic10 = new pic();
        pic12 = new pic();
        pic11 = new pic();
        pic15 = new pic();
        pic14 = new pic();
        pic13 = new pic();
        pic16 = new pic();
        pic20 = new pic();
        pic18 = new pic();
        pic17 = new pic();
        pic19 = new pic();
        pic21 = new pic();
        Hint_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        javax.swing.GroupLayout pic1Layout = new javax.swing.GroupLayout(pic1);
        pic1.setLayout(pic1Layout);
        pic1Layout.setHorizontalGroup(
            pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pic1Layout.setVerticalGroup(
            pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        start_btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        start_btn.setText("Start Game");
        start_btn.setPreferredSize(new java.awt.Dimension(80, 25));

        NoOFplayer_btn.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        NoOFplayer_btn.setText("Number of Players");
        NoOFplayer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoOFplayer_btnActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jButton8.setText("EXIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        noOFplayer_pnl.setBackground(new java.awt.Color(204, 204, 204));

        jRadioButton4.setText("4 Players");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("2 Players");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("3 Players");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("5 Players");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setText("6 Players");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        pic2.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic2Layout = new javax.swing.GroupLayout(pic2);
        pic2.setLayout(pic2Layout);
        pic2Layout.setHorizontalGroup(
            pic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic2Layout.setVerticalGroup(
            pic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic3.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic3Layout = new javax.swing.GroupLayout(pic3);
        pic3.setLayout(pic3Layout);
        pic3Layout.setHorizontalGroup(
            pic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic3Layout.setVerticalGroup(
            pic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        player1_btn.setText("player1");
        player1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1_btnActionPerformed(evt);
            }
        });

        player2_btn.setText("player2");
        player2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2_btnActionPerformed(evt);
            }
        });

        player4_btn.setText("player4");
        player4_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player4_btnActionPerformed(evt);
            }
        });

        player3_btn.setText("player3");
        player3_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player3_btnActionPerformed(evt);
            }
        });

        player5_btn.setText("player5");
        player5_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player5_btnActionPerformed(evt);
            }
        });

        player6_btn.setText("player6");
        player6_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player6_btnActionPerformed(evt);
            }
        });

        jColorChooser1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jColorChooser1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jColorChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jColorChooser1MouseClicked(evt);
            }
        });

        pic5.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic5Layout = new javax.swing.GroupLayout(pic5);
        pic5.setLayout(pic5Layout);
        pic5Layout.setHorizontalGroup(
            pic5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic5Layout.setVerticalGroup(
            pic5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic4.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic4Layout = new javax.swing.GroupLayout(pic4);
        pic4.setLayout(pic4Layout);
        pic4Layout.setHorizontalGroup(
            pic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic4Layout.setVerticalGroup(
            pic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic6.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic6Layout = new javax.swing.GroupLayout(pic6);
        pic6.setLayout(pic6Layout);
        pic6Layout.setHorizontalGroup(
            pic6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic6Layout.setVerticalGroup(
            pic6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic7.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic7Layout = new javax.swing.GroupLayout(pic7);
        pic7.setLayout(pic7Layout);
        pic7Layout.setHorizontalGroup(
            pic7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic7Layout.setVerticalGroup(
            pic7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic9.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic9Layout = new javax.swing.GroupLayout(pic9);
        pic9.setLayout(pic9Layout);
        pic9Layout.setHorizontalGroup(
            pic9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic9Layout.setVerticalGroup(
            pic9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic8.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic8Layout = new javax.swing.GroupLayout(pic8);
        pic8.setLayout(pic8Layout);
        pic8Layout.setHorizontalGroup(
            pic8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic8Layout.setVerticalGroup(
            pic8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic10.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic10Layout = new javax.swing.GroupLayout(pic10);
        pic10.setLayout(pic10Layout);
        pic10Layout.setHorizontalGroup(
            pic10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic10Layout.setVerticalGroup(
            pic10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic12.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic12Layout = new javax.swing.GroupLayout(pic12);
        pic12.setLayout(pic12Layout);
        pic12Layout.setHorizontalGroup(
            pic12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic12Layout.setVerticalGroup(
            pic12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic11.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic11Layout = new javax.swing.GroupLayout(pic11);
        pic11.setLayout(pic11Layout);
        pic11Layout.setHorizontalGroup(
            pic11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic11Layout.setVerticalGroup(
            pic11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic15.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic15Layout = new javax.swing.GroupLayout(pic15);
        pic15.setLayout(pic15Layout);
        pic15Layout.setHorizontalGroup(
            pic15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic15Layout.setVerticalGroup(
            pic15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic14.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic14Layout = new javax.swing.GroupLayout(pic14);
        pic14.setLayout(pic14Layout);
        pic14Layout.setHorizontalGroup(
            pic14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic14Layout.setVerticalGroup(
            pic14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic13.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic13Layout = new javax.swing.GroupLayout(pic13);
        pic13.setLayout(pic13Layout);
        pic13Layout.setHorizontalGroup(
            pic13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic13Layout.setVerticalGroup(
            pic13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic16.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic16Layout = new javax.swing.GroupLayout(pic16);
        pic16.setLayout(pic16Layout);
        pic16Layout.setHorizontalGroup(
            pic16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic16Layout.setVerticalGroup(
            pic16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic20.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic20Layout = new javax.swing.GroupLayout(pic20);
        pic20.setLayout(pic20Layout);
        pic20Layout.setHorizontalGroup(
            pic20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic20Layout.setVerticalGroup(
            pic20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic18.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic18Layout = new javax.swing.GroupLayout(pic18);
        pic18.setLayout(pic18Layout);
        pic18Layout.setHorizontalGroup(
            pic18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic18Layout.setVerticalGroup(
            pic18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic17.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic17Layout = new javax.swing.GroupLayout(pic17);
        pic17.setLayout(pic17Layout);
        pic17Layout.setHorizontalGroup(
            pic17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic17Layout.setVerticalGroup(
            pic17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic19.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic19Layout = new javax.swing.GroupLayout(pic19);
        pic19.setLayout(pic19Layout);
        pic19Layout.setHorizontalGroup(
            pic19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic19Layout.setVerticalGroup(
            pic19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        pic21.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout pic21Layout = new javax.swing.GroupLayout(pic21);
        pic21.setLayout(pic21Layout);
        pic21Layout.setHorizontalGroup(
            pic21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        pic21Layout.setVerticalGroup(
            pic21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        Hint_lbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 18)); // NOI18N

        javax.swing.GroupLayout noOFplayer_pnlLayout = new javax.swing.GroupLayout(noOFplayer_pnl);
        noOFplayer_pnl.setLayout(noOFplayer_pnlLayout);
        noOFplayer_pnlLayout.setHorizontalGroup(
            noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                .addComponent(pic19, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pic18, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pic17, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(pic20, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pic21, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jRadioButton5))
                            .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jRadioButton2))
                                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                        .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pic3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(jRadioButton3))
                                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                        .addComponent(pic6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pic4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pic5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton6)
                                    .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                            .addComponent(pic15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(pic16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                            .addComponent(pic14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(pic13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pic11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pic9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(62, 62, 62))
                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                        .addComponent(pic10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pic12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                        .addComponent(pic7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pic8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(jRadioButton4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)))
                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noOFplayer_pnlLayout.createSequentialGroup()
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(player4_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(player1_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(player2_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(player5_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(player3_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(player6_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hint_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        noOFplayer_pnlLayout.setVerticalGroup(
            noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pic3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pic8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pic7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pic12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pic10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pic6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pic4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pic5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pic17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pic18, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pic19, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pic20, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pic21, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton5))
                    .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                        .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noOFplayer_pnlLayout.createSequentialGroup()
                                .addComponent(pic9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pic11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noOFplayer_pnlLayout.createSequentialGroup()
                                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pic13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pic14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pic16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pic15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton6)))
                .addGap(11, 11, 11))
            .addGroup(noOFplayer_pnlLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1_btn)
                    .addComponent(player2_btn)
                    .addComponent(player3_btn))
                .addGap(20, 20, 20)
                .addGroup(noOFplayer_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player4_btn)
                    .addComponent(player5_btn)
                    .addComponent(player6_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hint_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoOFplayer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(noOFplayer_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(NoOFplayer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noOFplayer_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jColorChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jColorChooser1MouseClicked
        
       
    }//GEN-LAST:event_jColorChooser1MouseClicked
     boolean hint=false;
    public void setplayerColor(int idx){
         Color color =  jColorChooser1.getColor();
         System.out.println(color);
        
         int i=0;
         boolean choosed = false;
         while (i<6){
             
             if(color.equals(p[i].getColor())){
                 Hint_lbl.setText("Please, Select anothor color !");
                
                 choosed = true;
             }
             i++;
         }
         if (choosed == false) p[idx].setColor(color);
        

    }
    
    private void player1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1_btnActionPerformed
           // TODO add your handling code here:
            setplayerColor(0);
            player1_btn.setBackground(p[0].getColor());
           
        
    }//GEN-LAST:event_player1_btnActionPerformed

    private void player3_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player3_btnActionPerformed
        // TODO add your handling code here:
        setplayerColor(2);
        player3_btn.setBackground(p[2].getColor());
       
    }//GEN-LAST:event_player3_btnActionPerformed

    private void player5_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player5_btnActionPerformed
        // TODO add your handling code here:
        setplayerColor(4);
        player5_btn.setBackground(p[4].getColor());
       
    }//GEN-LAST:event_player5_btnActionPerformed

    private void player2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2_btnActionPerformed
        // TODO add your handling code here:
        setplayerColor(1);
        player2_btn.setBackground(p[1].getColor());
        
    }//GEN-LAST:event_player2_btnActionPerformed

    private void player4_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player4_btnActionPerformed
        // TODO add your handling code here:
        setplayerColor(3);
        player4_btn.setBackground(p[3].getColor());
       
    }//GEN-LAST:event_player4_btnActionPerformed

    private void player6_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player6_btnActionPerformed
        // TODO add your handling code here:
        setplayerColor(5);
        player6_btn.setBackground(p[5].getColor());
       
    }//GEN-LAST:event_player6_btnActionPerformed

    private void NoOFplayer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoOFplayer_btnActionPerformed
        noOFplayer_pnl.setVisible(true);
    }//GEN-LAST:event_NoOFplayer_btnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
        player1_btn.setVisible(true);
        player2_btn.setVisible(true);
        player3_btn.setVisible(true);
        player4_btn.setVisible(true);
        player5_btn.setVisible(false);
        player6_btn.setVisible(false);
        jColorChooser1.setVisible(true);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
        player1_btn.setVisible(true);
        player2_btn.setVisible(true);
        player3_btn.setVisible(false);
        player4_btn.setVisible(false);
        player5_btn.setVisible(false);
        player6_btn.setVisible(false);
        jColorChooser1.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
       
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
        player1_btn.setVisible(true);
        player2_btn.setVisible(true);
        player3_btn.setVisible(true);
        player4_btn.setVisible(false);
        player5_btn.setVisible(false);
        player6_btn.setVisible(false);
        jColorChooser1.setVisible(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
       
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false);
        player1_btn.setVisible(true);
        player2_btn.setVisible(true);
        player3_btn.setVisible(true);
        player4_btn.setVisible(true);
        player5_btn.setVisible(true);
        player6_btn.setVisible(false);
        
        jColorChooser1.setVisible(true);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
       
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(true);
        player1_btn.setVisible(true);
        player2_btn.setVisible(true);
        player3_btn.setVisible(true);
        player4_btn.setVisible(true);
        player5_btn.setVisible(true);
        player6_btn.setVisible(true);
        jColorChooser1.setVisible(true);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hint_lbl;
    private javax.swing.JButton NoOFplayer_btn;
    private javax.swing.JButton jButton8;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JPanel noOFplayer_pnl;
    private pic pic1;
    private pic pic10;
    private pic pic11;
    private pic pic12;
    private pic pic13;
    private pic pic14;
    private pic pic15;
    private pic pic16;
    private pic pic17;
    private pic pic18;
    private pic pic19;
    private pic pic2;
    private pic pic20;
    private pic pic21;
    private pic pic3;
    private pic pic4;
    private pic pic5;
    private pic pic6;
    private pic pic7;
    private pic pic8;
    private pic pic9;
    private javax.swing.JButton player1_btn;
    private javax.swing.JButton player2_btn;
    private javax.swing.JButton player3_btn;
    private javax.swing.JButton player4_btn;
    private javax.swing.JButton player5_btn;
    private javax.swing.JButton player6_btn;
    private javax.swing.JButton start_btn;
    // End of variables declaration//GEN-END:variables
}
