/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GamePlay0;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;

/**
 *
 * @author A.LoOotfy
 */
public class trade_pnl extends javax.swing.JPanel {

    /**
     * Creates new form trade_pnl
     */
        
        
    private   Zone z;
    private Player p;
    private Player p_withdeal;
    public trade_pnl() {
        initComponents();
        z = new Zone();
        p = new  Player();
        p_withdeal = new Player();
       /* id_lbl1.setText( Integer.valueOf().toString());
       
        id_lbl2.setText(Integer.valueOf().toString());
        cityname_lbl.setText(Integer.toString();*/
    }

    public Zone getZ() {
        return z;
    }

    public void setZ(Zone z) {
        this.z = z;
    }

    public Player getP() {
        return p;
    }

    public void setP(Player p) {
        this.p = p;
    }

    public Player getP_withdeal() {
        return p_withdeal;
    }

    public void setP_withdeal(Player p_withdeal) {
        this.p_withdeal = p_withdeal;
    }

    public JLabel getCityname_lbl() {
        return cityname_lbl;
    }

    public void setCityname_lbl(JLabel cityname_lbl) {
        this.cityname_lbl = cityname_lbl;
    }

    public JLabel getId_lbl1() {
        return id_lbl1;
    }

    public void setId_lbl1(JLabel id_lbl1) {
        this.id_lbl1 = id_lbl1;
    }

    public JLabel getId_lbl2() {
        return id_lbl2;
    }

    public void setId_lbl2(JLabel id_lbl2) {
        this.id_lbl2 = id_lbl2;
    }

    public JTextField getMoney_txt() {
        return money_txt;
    }
    
     public boolean trade(Player p_withtrade , Player p , Zone z){
         // System.out.println(z.getM_rent());
          Map<Integer,Zone> zoneMap = new HashMap<Integer,Zone>();
        // Gameplay g = new Gameplay();
         //zoneMap = g.getZoneMap();
          System.out.println(p.m_zonesOwnedIndexes.contains(z.getM_index()));
       
        if(p.m_zonesOwnedIndexes.contains(z.getM_index())){
            if(p_withtrade.getM_balance() >=  Integer.valueOf(money_txt.getText())){
               return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cityname_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id_lbl1 = new javax.swing.JLabel();
        id_lbl2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        money_txt = new javax.swing.JTextField();
        Deal_btn = new javax.swing.JButton();
        NoDeal_btn = new javax.swing.JButton();
        jlabel3 = new javax.swing.JLabel();

        cityname_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cityname_lbl.setText("city name");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Player ID");

        id_lbl1.setText("jLabel1");

        id_lbl2.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Trade With");

        money_txt.setText("Money");

        Deal_btn.setText("Deal");
        Deal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deal_btnActionPerformed(evt);
            }
        });

        NoDeal_btn.setText("No Deal");

        jlabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlabel3.setText("Player ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cityname_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(money_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NoDeal_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Deal_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(cityname_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Deal_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NoDeal_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(money_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  

    private void Deal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deal_btnActionPerformed
        // TODO add your handling code here:
       
        System.out.println(p.getM_id());
         Map<Integer,Zone> zoneMap = new HashMap<Integer,Zone>();
        // Gameplay g = new Gameplay();
        // zoneMap = g.getZoneMap();
        
     
        if(trade(p_withdeal, p, z)){
            p.setM_balance(p.getM_balance() + Integer.valueOf(money_txt.getText()));
            p_withdeal.setM_balance(p_withdeal.getM_balance() - Integer.valueOf(money_txt.getText()));
              //PlayerCurrentPostion x = g.getPos();
            // z = zoneMap.get(x.getCurrentPos(p_withdeal));
            p_withdeal.m_zonesOwnedIndexes.add(z.getM_index());
            p.m_zonesOwnedIndexes.remove(0);
           // g.getjLabel3().setText(String.valueOf( p.getM_balance()));
           // g.getjLabel6().setText(String.valueOf( p_withdeal.getM_balance()));
         //  g.updateBalance();
            System.out.println("done");
        }
         
    
    }//GEN-LAST:event_Deal_btnActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deal_btn;
    private javax.swing.JButton NoDeal_btn;
    private javax.swing.JLabel cityname_lbl;
    private javax.swing.JLabel id_lbl1;
    private javax.swing.JLabel id_lbl2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JTextField money_txt;
    // End of variables declaration//GEN-END:variables
}
